load("tests.bzl", "bf_integration_test")

bf_integration_test(
    input = "hello_world",
)

bf_integration_test(
    input = "stresstest",
)

bf_integration_test(
    size = "large",
    input = "mandelbrot",
)
